# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: x_skjh

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1-15 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: skjh
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master ${{ secrets.C_URL }} ~/scripts
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【食客江湖】'
        run: |
          cd ~/scripts
          node x_skjh.js
        env:
          SKJH: ${{ secrets.SKJH }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
