# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: x_zqwn

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,8 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: zqwn
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master ${{ secrets.C_URL }} ~/scripts
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: 'è¿è¡Œ ã€æœ€å¼ºèœ—ç‰›ğŸŒã€‘'
        run: |
          cd ~/scripts
          node x_zqwn.js
        env:
          ZQCK: ${{ secrets.ZQCK }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
